from app import app, db, Products, Categories, PC

categories_list = [
    {'category_id': 'C01', 'category_name': 'Fruits and Vegetables'},
    {'category_id': 'C02', 'category_name': 'Munchies'},
    {'category_id': 'C03', 'category_name': 'Sweet Tooth'},
    {'category_id': 'C04', 'category_name': 'Biscuits and Bakery'},
    {'category_id': 'C05', 'category_name': 'Dairy and Breakfast'},
    {'category_id': 'C06', 'category_name': 'Cold Drink and Juices'},
    {'category_id': 'C07', 'category_name': 'Instant and Frozen Food'},
    {'category_id': 'C08', 'category_name': 'Tea, Coffee and Heath Drinks'},
    {'category_id': 'C09', 'category_name': 'Atta, Rice and Dal'},
    {'category_id': 'C10', 'category_name': 'Dry Fruits, Masala and Oil'},
    {'category_id': 'C11', 'category_name': 'Sauces and Spreads'},
    {'category_id': 'C12', 'category_name': 'Perosnal Care'},
    {'category_id': 'C13', 'category_name': 'Home and Office'},
    {'category_id': 'C14', 'category_name': 'Baby Care'},
    {'category_id': 'C15', 'category_name': 'Cleaning Essentials'},
    {'category_id': 'C16', 'category_name': 'Pet Care'}
]

products_list = [
    {'product_id': 'P001', 'product_name': 'Apple', 'product_descp': "0.5Kg", 'product_pr': 120, 'product_qty':100},
    {'product_id': 'P002', 'product_name': 'Banana', 'product_descp': "1Pcs", 'product_pr': 10, 'product_qty':100},
    {'product_id': 'P003', 'product_name': 'Tomato', 'product_descp': "0.5Kg", 'product_pr': 80, 'product_qty':100},
    {'product_id': 'P004', 'product_name': 'Potato', 'product_descp': "0.5Kg", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P005', 'product_name': 'Cauliflower', 'product_descp': "1Pcs", 'product_pr': 50, 'product_qty':100},
    {'product_id': 'P006', 'product_name': 'Strawberry', 'product_descp': "250Gms", 'product_pr': 150, 'product_qty':100},
    {'product_id': 'P007', 'product_name': 'Lady Finger', 'product_descp': "0.5Kg", 'product_pr': 70, 'product_qty':100},
    {'product_id': 'P008', 'product_name': 'Orange Lays', 'product_descp': "1Pckt", 'product_pr': 20, 'product_qty':100},
    {'product_id': 'P009', 'product_name': 'Doritos', 'product_descp': "1Pckt", 'product_pr': 20, 'product_qty':100},
    {'product_id': 'P010', 'product_name': 'Sizzlin Cornitos', 'product_descp': "1Pckt", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P011', 'product_name': 'Masala Makhana', 'product_descp': "1Pckt", 'product_pr': 60, 'product_qty':100},
    {'product_id': 'P012', 'product_name': 'Mixed Farsan', 'product_descp': "1Pckt", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P013', 'product_name': 'Veggie Stix', 'product_descp': "1Pckt", 'product_pr': 20, 'product_qty':100},
    {'product_id': 'P014', 'product_name': 'Pringles', 'product_descp': "1Pckt", 'product_pr': 100, 'product_qty':100},
    {'product_id': 'P015', 'product_name': 'Cadbury DairyMilk', 'product_descp': "100Gms", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P016', 'product_name': 'Twix', 'product_descp': "150Gms", 'product_pr': 60, 'product_qty':100},
    {'product_id': 'P017', 'product_name': 'KitKat', 'product_descp': "50Gms", 'product_pr': 20, 'product_qty':100},
    {'product_id': 'P018', 'product_name': 'Chocolate Ice Cream', 'product_descp': "0.5Kg", 'product_pr': 300, 'product_qty':100},
    {'product_id': 'P019', 'product_name': 'Strawberry Ice Cream', 'product_descp': "0.5Kg", 'product_pr': 350, 'product_qty':100},
    {'product_id': 'P020', 'product_name': 'Matka Kulfi', 'product_descp': "150Gms", 'product_pr': 60, 'product_qty':100},
    {'product_id': 'P021', 'product_name': 'Vanilla Cup', 'product_descp': "20Gms", 'product_pr': 20, 'product_qty':100},
    {'product_id': 'P022', 'product_name': 'Chocochip Cookies', 'product_descp': "1Pckt", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P023', 'product_name': 'Hide N Seek Biscuits', 'product_descp': "1Pckt", 'product_pr': 35, 'product_qty':100},
    {'product_id': 'P024', 'product_name': 'Fruits N Nuts Cookies', 'product_descp': "1Pckt", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P025', 'product_name': 'Banana Cake', 'product_descp': "1Pckt", 'product_pr': 120, 'product_qty':100},
    {'product_id': 'P026', 'product_name': 'Vanilla Muffins', 'product_descp': "1Pckt", 'product_pr': 60, 'product_qty':100},
    {'product_id': 'P027', 'product_name': 'Chocolate Cake', 'product_descp': "1Pckt", 'product_pr': 120, 'product_qty':100},
    {'product_id': 'P028', 'product_name': 'Coconut Biscuits', 'product_descp': "1Pckt", 'product_pr': 50, 'product_qty':100},
    {'product_id': 'P029', 'product_name': 'Milk', 'product_descp': "1Ltr", 'product_pr': 60, 'product_qty':100},
    {'product_id': 'P030', 'product_name': 'Curd', 'product_descp': "0.5Ltr", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P031', 'product_name': 'Ghee', 'product_descp': "0.5Ltr", 'product_pr': 50, 'product_qty':100},
    {'product_id': 'P032', 'product_name': 'Chocos', 'product_descp': "1.2Kg", 'product_pr': 500, 'product_qty':100},
    {'product_id': 'P033', 'product_name': 'Cornflakes', 'product_descp': "1.5Kg", 'product_pr': 475, 'product_qty':100},
    {'product_id': 'P034', 'product_name': 'Toasts', 'product_descp': "1Pckt", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P035', 'product_name': 'Honey Loops', 'product_descp': "0.5Kg", 'product_pr': 150, 'product_qty':100},
    {'product_id': 'P036', 'product_name': 'Coco-Cola', 'product_descp': "1Ltr", 'product_pr': 70, 'product_qty':100},
    {'product_id': 'P037', 'product_name': 'Moutain Dew', 'product_descp': "500ml", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P038', 'product_name': 'Sprite', 'product_descp': "1Ltr", 'product_pr': 60, 'product_qty':100},
    {'product_id': 'P039', 'product_name': 'Jeeru', 'product_descp': "500ml", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P040', 'product_name': 'Mixed Fruit Juice', 'product_descp': "1Ltr", 'product_pr': 120, 'product_qty':100},
    {'product_id': 'P041', 'product_name': 'Mango Juice', 'product_descp': "1Ltr", 'product_pr': 120, 'product_qty':100},
    {'product_id': 'P042', 'product_name': 'Apple Juice', 'product_descp': "1Ltr", 'product_pr': 120, 'product_qty':100},
    {'product_id': 'P043', 'product_name': 'McCain Fries', 'product_descp': "0.5Kg", 'product_pr': 150, 'product_qty':100},
    {'product_id': 'P044', 'product_name': 'Maggie Noodles', 'product_descp': "1Pckt", 'product_pr': 70, 'product_qty':100},
    {'product_id': 'P045', 'product_name': 'Maggie Pasta', 'product_descp': "1Pckt", 'product_pr': 30, 'product_qty':100},
    {'product_id': 'P046', 'product_name': 'Yummizies Chicken Nuggets', 'product_descp': "1Kg", 'product_pr': 350, 'product_qty':100},
    {'product_id': 'P047', 'product_name': 'McCain Aloo Tikki', 'product_descp': "0.5Kg", 'product_pr': 150, 'product_qty':100},
    {'product_id': 'P048', 'product_name': 'Yummizies Seekh Kebab', 'product_descp': "1Kg", 'product_pr': 350, 'product_qty':100},
    {'product_id': 'P049', 'product_name': 'Maggie Cup Noodles', 'product_descp': "1Pckt", 'product_pr': 50, 'product_qty':100},
    {'product_id': 'P050', 'product_name': 'Masala Tea', 'product_descp': "0.5Kg", 'product_pr': 100, 'product_qty':100},
    {'product_id': 'P051', 'product_name': 'Nescafe Coffee', 'product_descp': "0.5Kg", 'product_pr': 200, 'product_qty':100},
    {'product_id': 'P052', 'product_name': 'Bourn Vita', 'product_descp': "0.5Kg", 'product_pr': 150, 'product_qty':100},
    {'product_id': 'P053', 'product_name': 'Cold Coffee Can', 'product_descp': "250ml", 'product_pr': 50, 'product_qty':100},
    {'product_id': 'P054', 'product_name': 'RedBull', 'product_descp': "250ml", 'product_pr': 100, 'product_qty':100},
    {'product_id': 'P055', 'product_name': 'Complain', 'product_descp': "0.5Kg", 'product_pr': 150, 'product_qty':100},
    {'product_id': 'P056', 'product_name': 'Yakult', 'product_descp': "1Pckt", 'product_pr': 100, 'product_qty':100},
    {'product_id': 'P057', 'product_name': 'Atta', 'product_descp': "0.5Kg", 'product_pr': 70, 'product_qty':100},
    {'product_id': 'P058', 'product_name': 'Rice', 'product_descp': "0.5Kg", 'product_pr': 80, 'product_qty':100},
    {'product_id': 'P059', 'product_name': 'Maida', 'product_descp': "0.5Kg", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P060', 'product_name': 'Channa Dal', 'product_descp': "0.5Kg", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P061', 'product_name': 'Rajma', 'product_descp': "0.5Kg", 'product_pr': 70, 'product_qty':100},
    {'product_id': 'P062', 'product_name': 'Soya Chunks', 'product_descp': "0.5Kg", 'product_pr': 60, 'product_qty':100},
    {'product_id': 'P063', 'product_name': 'Chick peas', 'product_descp': "0.5Kg", 'product_pr': 50, 'product_qty':100},
    {'product_id': 'P064', 'product_name': 'Almonds', 'product_descp': "0.5Kg", 'product_pr': 300, 'product_qty':100},
    {'product_id': 'P065', 'product_name': 'Cashews', 'product_descp': "0.5Kg", 'product_pr': 300, 'product_qty':100},
    {'product_id': 'P066', 'product_name': 'Salt', 'product_descp': "0.5Kg", 'product_pr': 80, 'product_qty':100},
    {'product_id': 'P067', 'product_name': 'Chaat Masala', 'product_descp': "100Gms", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P068', 'product_name': 'Sambar Masala', 'product_descp': "100Gms", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P069', 'product_name': 'Garam Masala', 'product_descp': "100Gms", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P070', 'product_name': 'Sunflower Oil', 'product_descp': "1Ltr", 'product_pr': 100, 'product_qty':100},
    {'product_id': 'P071', 'product_name': 'Tomato Ketchup', 'product_descp': "500ml", 'product_pr': 170, 'product_qty':100},
    {'product_id': 'P072', 'product_name': 'Mayonnaise', 'product_descp': "500ml", 'product_pr': 150, 'product_qty':100},
    {'product_id': 'P073', 'product_name': 'Sweet N Chilli Sauce', 'product_descp': "250ml", 'product_pr': 100, 'product_qty':100},
    {'product_id': 'P074', 'product_name': 'Soy Sauce', 'product_descp': "250ml", 'product_pr': 80, 'product_qty':100},
    {'product_id': 'P075', 'product_name': 'Vinegar', 'product_descp': "250ml", 'product_pr': 80, 'product_qty':100},
    {'product_id': 'P076', 'product_name': 'Chocolate Spread', 'product_descp': "500ml", 'product_pr': 200, 'product_qty':100},
    {'product_id': 'P077', 'product_name': 'Nutella', 'product_descp': "500ml", 'product_pr': 500, 'product_qty':100},
    {'product_id': 'P078', 'product_name': 'Bathing Soap', 'product_descp': "1Pcs", 'product_pr': 40, 'product_qty':100},
    {'product_id': 'P079', 'product_name': 'Toothpaste', 'product_descp': "1Pckt", 'product_pr': 50, 'product_qty':100},
    {'product_id': 'P080', 'product_name': 'Shampoo', 'product_descp': "500ml", 'product_pr': 150, 'product_qty':100},
    {'product_id': 'P081', 'product_name': 'Conditioner', 'product_descp': "500ml", 'product_pr': 120, 'product_qty':100},
    {'product_id': 'P082', 'product_name': 'Face Wash', 'product_descp': "250ml", 'product_pr': 70, 'product_qty':100},
    {'product_id': 'P083', 'product_name': 'Body Moisturizer', 'product_descp': "500ml", 'product_pr': 250, 'product_qty':100},
    {'product_id': 'P084', 'product_name': 'Talcum Powder', 'product_descp': "0.5Kg", 'product_pr': 150, 'product_qty':100},
    {'product_id': 'P085', 'product_name': 'Tissue Box', 'product_descp': "1Pckt", 'product_pr': 80, 'product_qty':100},
    {'product_id': 'P086', 'product_name': 'Air Freshner', 'product_descp': "1Pcs", 'product_pr': 50, 'product_qty':100},
    {'product_id': 'P087', 'product_name': 'Tiffin Box', 'product_descp': "1Pcs", 'product_pr': 100, 'product_qty':100},
    {'product_id': 'P088', 'product_name': 'Aluminium Foil', 'product_descp': "1Pckt", 'product_pr': 70, 'product_qty':100},
    {'product_id': 'P089', 'product_name': 'Paper Plates', 'product_descp': "10Pcs", 'product_pr': 100, 'product_qty':100},
    {'product_id': 'P090', 'product_name': 'Containers', 'product_descp': "2Pcs", 'product_pr': 200, 'product_qty':100},
    {'product_id': 'P091', 'product_name': 'Mosquito Repellent', 'product_descp': "1Pckt", 'product_pr': 50, 'product_qty':100},
    {'product_id': 'P092', 'product_name': 'Baby Shampoo', 'product_descp': "500ml", 'product_pr': 100, 'product_qty':100},
    {'product_id': 'P093', 'product_name': 'Baby Soap', 'product_descp': "1Pcs", 'product_pr': 70, 'product_qty':100},
    {'product_id': 'P094', 'product_name': 'Baby Wet Wipes', 'product_descp': "1Pckt", 'product_pr': 150, 'product_qty':100},
    {'product_id': 'P095', 'product_name': 'Baby Powder', 'product_descp': "250gms", 'product_pr': 100, 'product_qty':100},
    {'product_id': 'P096', 'product_name': 'Baby Diapers', 'product_descp': "1Pckt", 'product_pr': 300, 'product_qty':100},
    {'product_id': 'P097', 'product_name': 'Bsby Food', 'product_descp': "0.5Kg", 'product_pr': 200, 'product_qty':100},
    {'product_id': 'P098', 'product_name': 'Baby Massage Oil', 'product_descp': "500ml", 'product_pr': 150, 'product_qty':100},
    {'product_id': 'P099', 'product_name': 'Harpic Toilet Cleaner', 'product_descp': "500ml", 'product_pr': 70, 'product_qty':100},
    {'product_id': 'P100', 'product_name': 'Tide Powder', 'product_descp': "0.5Kg", 'product_pr': 50, 'product_qty':100},
    {'product_id': 'P101', 'product_name': 'Wheel Powder', 'product_descp': "0.5Kg", 'product_pr': 50, 'product_qty':100},
    {'product_id': 'P102', 'product_name': 'Scotch Brite', 'product_descp': "1Pcs", 'product_pr': 20, 'product_qty':100},
    {'product_id': 'P103', 'product_name': 'Cleaning Cloth', 'product_descp': "1Pckt", 'product_pr': 75, 'product_qty':100},
    {'product_id': 'P104', 'product_name': 'Odonil', 'product_descp': "1Pckt", 'product_pr': 60, 'product_qty':100},
    {'product_id': 'P105', 'product_name': 'Broom', 'product_descp': "1Pcs", 'product_pr': 100, 'product_qty':100},
    {'product_id': 'P106', 'product_name': 'Dog Food', 'product_descp': "1Kg", 'product_pr': 250, 'product_qty':100},
    {'product_id': 'P107', 'product_name': 'Cat Food', 'product_descp': "1Kg", 'product_pr': 250, 'product_qty':100},
    {'product_id': 'P108', 'product_name': 'Dog Chewies', 'product_descp': "1Pckt", 'product_pr': 150, 'product_qty':100},
    {'product_id': 'P109', 'product_name': 'Cat Knibbles', 'product_descp': "1Pckt", 'product_pr': 150, 'product_qty':100},
    {'product_id': 'P110', 'product_name': 'Soft Ball', 'product_descp': "1Pcs", 'product_pr': 80, 'product_qty':100},
    {'product_id': 'P111', 'product_name': 'Hair Shampoo', 'product_descp': "500ml", 'product_pr': 170, 'product_qty':100},
    {'product_id': 'P112', 'product_name': 'Pet Wipes', 'product_descp': "1Pckt", 'product_pr': 150, 'product_qty':100},
]

pc_list = [
    {'pc_id' : 'CP001', 'product_id' : 'P001', 'category_id' : 'C01'},
    {'pc_id' : 'CP002', 'product_id' : 'P002', 'category_id' : 'C01'},
    {'pc_id' : 'CP003', 'product_id' : 'P003', 'category_id' : 'C01'},
    {'pc_id' : 'CP004', 'product_id' : 'P004', 'category_id' : 'C01'},
    {'pc_id' : 'CP005', 'product_id' : 'P005', 'category_id' : 'C01'},
    {'pc_id' : 'CP006', 'product_id' : 'P006', 'category_id' : 'C01'},
    {'pc_id' : 'CP007', 'product_id' : 'P007', 'category_id' : 'C01'},
    {'pc_id' : 'CP008', 'product_id' : 'P008', 'category_id' : 'C02'},
    {'pc_id' : 'CP009', 'product_id' : 'P009', 'category_id' : 'C02'},
    {'pc_id' : 'CP010', 'product_id' : 'P010', 'category_id' : 'C02'},
    {'pc_id' : 'CP011', 'product_id' : 'P011', 'category_id' : 'C02'},
    {'pc_id' : 'CP012', 'product_id' : 'P012', 'category_id' : 'C02'},
    {'pc_id' : 'CP013', 'product_id' : 'P013', 'category_id' : 'C02'},
    {'pc_id' : 'CP014', 'product_id' : 'P014', 'category_id' : 'C02'},
    {'pc_id' : 'CP015', 'product_id' : 'P015', 'category_id' : 'C03'},
    {'pc_id' : 'CP016', 'product_id' : 'P016', 'category_id' : 'C03'},
    {'pc_id' : 'CP017', 'product_id' : 'P017', 'category_id' : 'C03'},
    {'pc_id' : 'CP018', 'product_id' : 'P018', 'category_id' : 'C03'},
    {'pc_id' : 'CP019', 'product_id' : 'P019', 'category_id' : 'C03'},
    {'pc_id' : 'CP020', 'product_id' : 'P020', 'category_id' : 'C03'},
    {'pc_id' : 'CP021', 'product_id' : 'P021', 'category_id' : 'C03'},
    {'pc_id' : 'CP022', 'product_id' : 'P022', 'category_id' : 'C04'},
    {'pc_id' : 'CP023', 'product_id' : 'P023', 'category_id' : 'C04'},
    {'pc_id' : 'CP024', 'product_id' : 'P024', 'category_id' : 'C04'},
    {'pc_id' : 'CP025', 'product_id' : 'P025', 'category_id' : 'C04'},
    {'pc_id' : 'CP026', 'product_id' : 'P026', 'category_id' : 'C04'},
    {'pc_id' : 'CP027', 'product_id' : 'P027', 'category_id' : 'C04'},
    {'pc_id' : 'CP028', 'product_id' : 'P028', 'category_id' : 'C04'},
    {'pc_id' : 'CP029', 'product_id' : 'P029', 'category_id' : 'C05'},
    {'pc_id' : 'CP030', 'product_id' : 'P030', 'category_id' : 'C05'},
    {'pc_id' : 'CP031', 'product_id' : 'P031', 'category_id' : 'C05'},
    {'pc_id' : 'CP032', 'product_id' : 'P032', 'category_id' : 'C05'},
    {'pc_id' : 'CP033', 'product_id' : 'P033', 'category_id' : 'C05'},
    {'pc_id' : 'CP034', 'product_id' : 'P034', 'category_id' : 'C05'},
    {'pc_id' : 'CP035', 'product_id' : 'P035', 'category_id' : 'C05'},
    {'pc_id' : 'CP036', 'product_id' : 'P036', 'category_id' : 'C06'},
    {'pc_id' : 'CP037', 'product_id' : 'P037', 'category_id' : 'C06'},
    {'pc_id' : 'CP038', 'product_id' : 'P038', 'category_id' : 'C06'},
    {'pc_id' : 'CP039', 'product_id' : 'P039', 'category_id' : 'C06'},
    {'pc_id' : 'CP040', 'product_id' : 'P040', 'category_id' : 'C06'},
    {'pc_id' : 'CP041', 'product_id' : 'P041', 'category_id' : 'C06'},
    {'pc_id' : 'CP042', 'product_id' : 'P042', 'category_id' : 'C06'},
    {'pc_id' : 'CP043', 'product_id' : 'P043', 'category_id' : 'C07'},
    {'pc_id' : 'CP044', 'product_id' : 'P044', 'category_id' : 'C07'},
    {'pc_id' : 'CP045', 'product_id' : 'P045', 'category_id' : 'C07'},
    {'pc_id' : 'CP046', 'product_id' : 'P046', 'category_id' : 'C07'},
    {'pc_id' : 'CP047', 'product_id' : 'P047', 'category_id' : 'C07'},
    {'pc_id' : 'CP048', 'product_id' : 'P048', 'category_id' : 'C07'},
    {'pc_id' : 'CP049', 'product_id' : 'P049', 'category_id' : 'C07'},
    {'pc_id' : 'CP050', 'product_id' : 'P050', 'category_id' : 'C08'},
    {'pc_id' : 'CP051', 'product_id' : 'P051', 'category_id' : 'C08'},
    {'pc_id' : 'CP052', 'product_id' : 'P052', 'category_id' : 'C08'},
    {'pc_id' : 'CP053', 'product_id' : 'P053', 'category_id' : 'C08'},
    {'pc_id' : 'CP054', 'product_id' : 'P054', 'category_id' : 'C08'},
    {'pc_id' : 'CP055', 'product_id' : 'P055', 'category_id' : 'C08'},
    {'pc_id' : 'CP056', 'product_id' : 'P056', 'category_id' : 'C08'},
    {'pc_id' : 'CP057', 'product_id' : 'P057', 'category_id' : 'C09'},
    {'pc_id' : 'CP058', 'product_id' : 'P058', 'category_id' : 'C09'},
    {'pc_id' : 'CP059', 'product_id' : 'P059', 'category_id' : 'C09'},
    {'pc_id' : 'CP060', 'product_id' : 'P060', 'category_id' : 'C09'},
    {'pc_id' : 'CP061', 'product_id' : 'P061', 'category_id' : 'C09'},
    {'pc_id' : 'CP062', 'product_id' : 'P062', 'category_id' : 'C09'},
    {'pc_id' : 'CP063', 'product_id' : 'P063', 'category_id' : 'C09'},
    {'pc_id' : 'CP064', 'product_id' : 'P064', 'category_id' : 'C10'},
    {'pc_id' : 'CP065', 'product_id' : 'P065', 'category_id' : 'C10'},
    {'pc_id' : 'CP066', 'product_id' : 'P066', 'category_id' : 'C10'},
    {'pc_id' : 'CP067', 'product_id' : 'P067', 'category_id' : 'C10'},
    {'pc_id' : 'CP068', 'product_id' : 'P068', 'category_id' : 'C10'},
    {'pc_id' : 'CP069', 'product_id' : 'P069', 'category_id' : 'C10'},
    {'pc_id' : 'CP070', 'product_id' : 'P070', 'category_id' : 'C10'},
    {'pc_id' : 'CP071', 'product_id' : 'P071', 'category_id' : 'C11'},
    {'pc_id' : 'CP072', 'product_id' : 'P072', 'category_id' : 'C11'},
    {'pc_id' : 'CP073', 'product_id' : 'P073', 'category_id' : 'C11'},
    {'pc_id' : 'CP074', 'product_id' : 'P074', 'category_id' : 'C11'},
    {'pc_id' : 'CP075', 'product_id' : 'P075', 'category_id' : 'C11'},
    {'pc_id' : 'CP076', 'product_id' : 'P076', 'category_id' : 'C11'},
    {'pc_id' : 'CP077', 'product_id' : 'P077', 'category_id' : 'C11'},
    {'pc_id' : 'CP078', 'product_id' : 'P078', 'category_id' : 'C12'},
    {'pc_id' : 'CP079', 'product_id' : 'P079', 'category_id' : 'C12'},
    {'pc_id' : 'CP080', 'product_id' : 'P080', 'category_id' : 'C12'},
    {'pc_id' : 'CP081', 'product_id' : 'P081', 'category_id' : 'C12'},
    {'pc_id' : 'CP082', 'product_id' : 'P082', 'category_id' : 'C12'},
    {'pc_id' : 'CP083', 'product_id' : 'P083', 'category_id' : 'C12'},
    {'pc_id' : 'CP084', 'product_id' : 'P084', 'category_id' : 'C12'},
    {'pc_id' : 'CP085', 'product_id' : 'P085', 'category_id' : 'C13'},
    {'pc_id' : 'CP086', 'product_id' : 'P086', 'category_id' : 'C13'},
    {'pc_id' : 'CP087', 'product_id' : 'P087', 'category_id' : 'C13'},
    {'pc_id' : 'CP088', 'product_id' : 'P088', 'category_id' : 'C13'},
    {'pc_id' : 'CP089', 'product_id' : 'P089', 'category_id' : 'C13'},
    {'pc_id' : 'CP090', 'product_id' : 'P090', 'category_id' : 'C13'},
    {'pc_id' : 'CP091', 'product_id' : 'P091', 'category_id' : 'C13'},
    {'pc_id' : 'CP092', 'product_id' : 'P092', 'category_id' : 'C14'},
    {'pc_id' : 'CP093', 'product_id' : 'P093', 'category_id' : 'C14'},
    {'pc_id' : 'CP094', 'product_id' : 'P094', 'category_id' : 'C14'},
    {'pc_id' : 'CP095', 'product_id' : 'P095', 'category_id' : 'C14'},
    {'pc_id' : 'CP096', 'product_id' : 'P096', 'category_id' : 'C14'},
    {'pc_id' : 'CP097', 'product_id' : 'P097', 'category_id' : 'C14'},
    {'pc_id' : 'CP098', 'product_id' : 'P098', 'category_id' : 'C14'},
    {'pc_id' : 'CP099', 'product_id' : 'P099', 'category_id' : 'C15'},
    {'pc_id' : 'CP100', 'product_id' : 'P100', 'category_id' : 'C15'},
    {'pc_id' : 'CP101', 'product_id' : 'P101', 'category_id' : 'C15'},
    {'pc_id' : 'CP102', 'product_id' : 'P102', 'category_id' : 'C15'},
    {'pc_id' : 'CP103', 'product_id' : 'P103', 'category_id' : 'C15'},
    {'pc_id' : 'CP104', 'product_id' : 'P104', 'category_id' : 'C15'},
    {'pc_id' : 'CP105', 'product_id' : 'P105', 'category_id' : 'C15'},
    {'pc_id' : 'CP106', 'product_id' : 'P106', 'category_id' : 'C16'},
    {'pc_id' : 'CP107', 'product_id' : 'P107', 'category_id' : 'C16'},
    {'pc_id' : 'CP108', 'product_id' : 'P108', 'category_id' : 'C16'},
    {'pc_id' : 'CP109', 'product_id' : 'P109', 'category_id' : 'C16'},
    {'pc_id' : 'CP110', 'product_id' : 'P110', 'category_id' : 'C16'},
    {'pc_id' : 'CP111', 'product_id' : 'P111', 'category_id' : 'C16'},
    {'pc_id' : 'CP112', 'product_id' : 'P112', 'category_id' : 'C16'}
]

with app.app_context():
    for category_data in categories_list:
        category = Categories(
            category_id=category_data['category_id'],
            category_name=category_data['category_name']
        )
        db.session.add(category)

    for product_data in products_list:
        product = Products(
            product_id=product_data['product_id'],
            product_name=product_data['product_name'],
            product_descp=product_data['product_descp'],
            product_pr=product_data['product_pr'],
            product_qty=product_data['product_qty']
        )
        db.session.add(product)

    for pc_data in pc_list:
        pc = PC(
            pc_id=pc_data['pc_id'],
            product_id=pc_data['product_id'],
            category_id=pc_data['category_id']
        )
        db.session.add(pc)

    db.session.commit()